spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yibantest?useSSL=false
    username: yibantest
    password: yibantest
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
